[tool.pytest.ini_options]
addopts = "-v --doctest-modules"

[tool.isort]
force_grid_wrap = 2
multi_line_output = 3
line_length = 79
include_trailing_comma = true

[tool.black]
line_length = 79

[tool.pylint.basic]
good-names = ["hp", "i", "j", "k"]
